sudo: required
services:
        - docker
before_install:
        - docker build -t travis_test -f Dockerfile.dev .

script:
        - docker run travis_test npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-ap-south-1-556026884725"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $aws_key
        secret_access_key:
                secure: "$aws_secret"
                 
